---
weight: 3
title: "02/05/2018 Group Meeting Notes"
author: "Rachel Steele"
output: html_document
---

## **MD Vs. Transcriptomics Data Decision**
It was decided that we will stick with the MD datasets

## **The game plan:**
* Get in groups and **make the code**
* Sufficiently **document the code** to start making a workshop manual/guide to follow during the workshop
* Meet with each other and **practice presenting** the material workshop style

## **Workshop flow**

### *Introduction*
* John will come up with good explanations for his data which are simple enough to understand and which will:
    * Highlight the terminology for the data (frame/energy values, distances between modeled atoms, etc.)
    * Define PCA components
    * Use pictures and video to give a clear understanding of what the data represents
    
### *Plots*

#### Scatterplots
* **Big data principles:**
    * use of faceting
    * Grid arrangement
* Using John's raw data, each of the 29 columns (representing features) of data can be represented:
    * X axis -- frame value/1,000
    * Y axis -- value
* Ming has already drafted code which will do this -- located under tutorials on our blogdown site

#### PCA Plotting
* **Big data principles:**
    * Using PCA to simplify relationships between multiple variable
* First column is the energy value of the frame
* Remaining columns are PCA scores
    * We will explain how to calculate the PCA score -- we can go into more detail on this process in supplemental materials. In addition, we can include some of the more complicated data pre-processing steps on the blogdown site.
    
#### Network Plot
* **Big data principles:**
    * Using networks to relate many data points to one another
* We will make two plots: 
    * The first will show how using all of the data for a network plot will result in a big messy network!
    * We will cluster the data into (200?) representative groups.
        * for MD data, the number of clusters is the square root of the number of frames
* We can use the clusters we make or the strength of the relationships found within the network plot for our heatmap plot.

#### Heatmap Plot
* **Big data principles:**
    * To pictorially represent data correlations, showing complex data in tabular format
* We can use the original data to make a big heat map
* We can use clustered data (clustered for network plot) to make a heat map
    * This would result in a 200x200 matrix
    * Using data after time-flatting, however, may be more informational
* We can use node strengths from the network plot to make a heat map
* We can use traditional pipelines for RNA-seq analysis to:
    * Cluster the data and make a dendrogram
    * Create a heatmap of clustered groups of the data
        * Examples available at Statonlab.github.io
        
## **Group Assignments:**
### *By 2/19/2018 each group should:*
* Come up with one or more **codes** for their respective plots
* **Document the code(s)** with comments and explanations
* Integrate the code and corresponding explanations into a **draft manual**
* Be prepared to **mock present** their code in workshop style format to the other group

### Heatmap and Network Plot Coding:
* Rachel
* Sanjeev
* Shawn
* Amanda
* Pawat

### Scatterplot and PCA Coding:
* Ming
* Jiali
* John
* Karthik
* Jennifer

## *Next Group Meeting*
* 2/19/2018 at 4:00 p.m.
* Ming will book a room in the library

