---
title: "Heatmap Tutorial"
author: "Rachel Steele"
date: "February 15, 2018"
output: md_document
---

# Import and parse data

```{r}
library(tidyr)
library(ggplot2)
library(reshape2)
data_path <- '../datasets/john_datasets/traj_0.dat'
feature_names = stringr::str_split(readLines(data_path)[1], '--')[[1]]

# feature names have space and special characters. These characters are not good for variable names.
# let's encode feature names
names(feature_names) = paste0('V_', 1:length(feature_names))
data_raw = read.table(data_path, header = FALSE, sep = ' ', comment.char = 'D', stringsAsFactors = FALSE)
colnames(data_raw) = names(feature_names)
str(data_raw)

# add frame index
data_raw$frame_index = 1:nrow(data_raw)
```
 
# Cluster data 
```{r}
#Set frame index as row names
rownames(data_raw) <- data_raw$frame_index
data_raw$frame_index <- NULL

#ensure NA values omitted
data_clean <- na.omit(data_raw)

#K-means cluster analysis using 5 clusters
fit <- kmeans(data_clean,5)

#get cluster means
aggregate(data_clean, by=list(fit$cluster), FUN=mean)

#append cluster assignment and id
data_kmean <- cbind(data_clean, id=seq(nrow(data_clean)), cluster=fit$cluster)

#add id sort to order id numbers by cluster
data_kmean$idsort <- data_kmean$id[order(data_kmean$cluster)]
data_kmean$ idsort <- order(data_kmean$idsort)

#reshape2:: melt to make data.frame in long format
data_long <- melt(data_kmean, id.vars=c("id", "idsort"))

#plot heatmap
ggplot(data_long, aes(x=variable, y=idsort)) +
  geom_tile(aes(fill=value))


#Hierarchical heatmap
#Convert clean data to matrix
data_matrix <- as.matrix(data_clean)

#plot heatmap
heatmap(data_matrix)
```

