---
weight: 2
title: "PCA plot"
author: "GST Data Visualization Group"
output: html_document
---

<style>
pre code, pre, code {
  white-space: pre !important;
  overflow-x: scroll !important;
  word-break: keep-all !important;
  word-wrap: initial !important;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(ellipse)
```



## Import data

```{r}
load(url('https://github.com/MingChen0919/gst-colloquium-workshop-2018/raw/master/content/datasets/datasets.RData'))
```


## Visualization

### Collective Variables vs. Macrostates 

```{r}
ggplot(energy_tics) +
  geom_point(aes(x = TIC0, y = TIC1, color = as.factor(macrostate)),
             stat = "identity", position = "identity") +
  coord_cartesian() +
  facet_null() +
  scale_x_continuous() +
  scale_y_continuous() +
  scale_color_manual(name = "Macrostate",
                     values = c("#7572ff", "#ff0000", "#f0ff00", "#22ff00", "#2200ff", "#7c00ff", "#e13535"),
                     limits = 0:6, breaks = 0:6) +
  theme_classic() +
  
  # helper functions
  xlab('TIC0') +
  ylab('TIC1')
```


### Collective Variables vs. Energy

```{r}
ggplot(energy_tics) +
  geom_point(aes(x = TIC0, y = TIC1, color = Energy),
             stat = "identity", position = "identity") +
  coord_cartesian() +
  facet_null() +
  scale_x_continuous() +
  scale_y_continuous() +
  scale_color_gradient(low="blue", high="red") +
  theme_classic() +
  
  # helper functions
  xlab('TIC0') +
  ylab('TIC1')
```




```{r eval=FALSE, echo=FALSE}
## calculate ellipses
df = pca_scores
df_ell <- data.frame()
for(g in levels(df$group)){
df_ell <- rbind(df_ell, cbind(as.data.frame(with(df[df$group==g,],
                                                 ellipse(cor(TIC0, TIC1), 
                                         scale=c(sd(TIC0),sd(TIC0)), 
                                         centre=c(mean(TIC0),mean(TIC0))))),group=g))
}

df_ell = data.frame()
for(g in 1:4) {
  x = pca_scores[pca_scores$group == g, ]$TIC0
  y = pca_scores[pca_scores$group == g, ]$TIC1
  df_ell = rbind(df_ell, cbind(ellipse(cor(x, y)), g = g))
}
```

```{r eval=FALSE, echo=FALSE}
ggplot(faithful, aes(waiting, eruptions, color = eruptions > 3)) +
  geom_point() +
  stat_ellipse(type = "norm", linetype = 2) +
  stat_ellipse(type = "t") +
  theme_classic()
```


#### References:
* [ref 1](http://rstudio-pubs-static.s3.amazonaws.com/53162_cd16ee63c24747459ccd180f69f07810.html)
* [ref 2](http://ggplot2.tidyverse.org/reference/stat_ellipse.html)
